### ISSUE TITLE
1.1. Prijava korisnika

### ISSUE THREAD

**Issue by mjakopane** [AIR-FOI-HR/AIR1914#1]
Korisnik se prijavljuje putem korisničkih podataka koje je dobio prilikom registracije u sustav.

**Comment by mjakopane** [comment]
Napravljen dizajn početnog zaslona i zaslona prijave te su povezani:
![image](https://user-images.githubusercontent.com/36993293/68995952-e7c6c680-0893-11ea-976d-5702d6166186.png)
![image](https://user-images.githubusercontent.com/36993293/68995954-ec8b7a80-0893-11ea-828b-3d7651ec0f7a.png)

Zaslon za prijavu dijelomično je implementiran. Pokušano je povezivanje s Web stranicom (https://airfood2go.000webhostapp.com/Stranice/Prijava.php) na kojoj se nalazi prijava za Web aplikaciju, no problem se javlja kod čitanja json odgovora. Trenutno još nemamo konkretno riješenje, ali u procesu popravka smo. Problem ćemo pokušat riješiti korištenjem retrofita za povezivanje na bazu podataka.

**Comment by njurcic** [comment]
Problem je riješen na način da smo se s bazom podataka povezali preko http klijenta. Kao posrednik u  komunikaciji bila nam je potrebna php datoteka (login.php) koja je postavljena na 000webhost. Jedini zadatak koji nam je ostao je povezati zaslon prijave s početnim zaslonom koji se treba prikazati korisniku nakon što se prijavi.

**Comment by mjakopane** [comment]
Zbog prijašnjih problema (nemogućnost spajanja na web servis) napravili smo vlastiti Web servis pomoću kojeg se spajamo na bazu podataka. Dovršena funkcionalnost za prijavu. Ako se korisnik prijavi s ispravnim korisničkim imenom i lozinkom, dobije obavijest da je prijava uspješna, u suprotnom obavijest da prijava nije uspješna.

**Comment by njurcic** [comment]
Dodana je provjera jesu li uneseni svi podaci, korisničko ime i lozinka, za prijavu. Ukoliko nisu, korisnika se obavijesti porukom, kao što je prikazano na slici, da je potrebno popuniti sve podatke. ![Screenshot_20191206-193404_FOOD2GO.jpg](https://images.zenhubusercontent.com/5dc2bd97586229000122a2c9/655f179d-956c-448e-abc3-1637ee7acf1f)
