### ISSUE TITLE
2.5. Odjava

### ISSUE THREAD

**Issue by mjakopane** [AIR-FOI-HR/AIR1914#10]
Kada korisnik želi zatvoriti aplikaciju, klikne na odjavu.

**Comment by njurcic** [comment]
Odjava je postavljena u navigacijski izbornik kao na slici ispod. 

![Screenshot_20191211-205832_FOOD2GO.jpg](https://images.zenhubusercontent.com/5dc2bd97586229000122a2c9/99a0b2f0-c6b9-4acb-8506-13bdc4520d0d)

**Comment by njurcic** [comment]
Ukoliko se korisnik želi odjaviti, aplikacija će mu to dopustiti ako je povezan na Internet. Također, dobit će poruku da se uspješno odjavio i to možemo vidjeti na sljedećoj slici.

![Screenshot_20191211-205839_FOOD2GO.jpg](https://images.zenhubusercontent.com/5dc2bd97586229000122a2c9/80199ddb-4710-475e-b7a9-575f2772e7a7)

**Comment by njurcic** [comment]
Ako korisnik nije povezan s Internetom, neće se moći odjaviti i dobit će poruku da se mora prije povezati na Internet. Takav prikaz, koji se u toj situaciji prikazuje korisniku, možemo vidjeti na slici ispod. 

![Screenshot_20191211-211039_FOOD2GO.jpg](https://images.zenhubusercontent.com/5dc2bd97586229000122a2c9/f981865b-09c5-456a-a05f-c9a4aca437ef)
