### ISSUE TITLE
3. Kategorije

### ISSUE THREAD

**Issue by mjakopane** [AIR-FOI-HR/AIR1914#11]
Početni zaslon nakon prijave u aplikaciju. Na tom zaslonu korisnik će moći vidjeti ponudu jela i pića putem kategorija.

**Comment by jakovnakic** [comment]
Napravljen je dizajn za zaslon kategorije - glavni zaslon; zaslon koji se otvara nakon uspješne korisnikove prijave.
![image.png](https://images.zenhubusercontent.com/5de96807af4031c7dba544f4/c92ef959-bb52-4f5f-bd2f-c33cea73cc69)

**Comment by jakovnakic** [comment]
Na zaslonu je implementirana funkcionalnost. Klikom na jednu od kategorija se ispiše odabrana kategorija.
