### ISSUE TITLE
3.1. Odabir kategorije

### ISSUE THREAD

**Issue by mjakopane** [AIR-FOI-HR/AIR1914#12]
Kada korisnik odabere određenu kategoriju, npr. piće, otvora mu se novi zaslon sa prikazom svih pića.

**Comment by jakovnakic** [comment]
Kreiran je layout za zaslona u kojem će se prikazivati svi artikli odabrane kategorije. Na vrhu se nalazi naslov zaslona, koji će ovisno o odabranoj kategoriji glasiti "Hrana" ili "Piće". Ispod naslova se nalazi recyclerview u kojemu će se nalaziti njegovi elementi odnosno pojedini artikli.
![image.png](https://images.zenhubusercontent.com/5de96807af4031c7dba544f4/e9318c5d-b5ad-4381-ab42-82f1944a973f)

**Comment by jakovnakic** [comment]
Napravljena je xml datoteka koja će služiti kao layout individualnog artikla odnosno elementa recyclerviewa. Svaki artikl će imati svoju sliku prikazanu u krugu, naziv, i cijenu.
![image.png](https://images.zenhubusercontent.com/5de96807af4031c7dba544f4/a08321e9-7d38-4238-8e83-88d26ddf2141)

**Comment by jakovnakic** [comment]
Implementirana je funkcionalnost - preko web servisa se dohvaćaju svi artikli odabrane kategorije i prikazuju na zaslonu preko recyclerviewa.
![image.png](https://images.zenhubusercontent.com/5de96807af4031c7dba544f4/59b168ee-5339-498b-a68e-4870eab86a6f)
