### ISSUE TITLE
3.1.1. Odabir potkategorije

### ISSUE THREAD

**Issue by mjakopane** [AIR-FOI-HR/AIR1914#13]
Kada korisnik odabere određenu kategoriju, npr. pića, otvara mu se zaslon sa svim pićima i pruža mu se mogućnost odabira određenog pića. Prilikom odabira određenog pića bit će prikazana cijena i gumb za odabir tog pića.

**Comment by jakovnakic** [comment]
Napravljen je dizajn zaslona na kojemu se prikazuju svi detalji odabranog artikla. Dostupni podaci su naziv artikla, slika, opis, i cijena. U donjem lijevom kutu se nalaze gumbovi za povećanje i smanjenje željene količine artikla, a desno se nalazi gumb za dodavanje artikla u košaricu.
![image.png](https://images.zenhubusercontent.com/5de96807af4031c7dba544f4/a0a30aa9-164d-49d6-8cb7-a85126935893)

**Comment by jakovnakic** [comment]
Implementirana je funkcionalnost. Klikom na gumbove "+" i "-" količina artikla se povećava odnosno smanjuje. Količina ne može biti manja od 1 ili veća od 100. Klikom na "Dodaj u košaricu" artikl se u odabranoj količini sprema u košaricu korisnika u kojoj su podaci o artiklima koje korisnik namjerava naručiti zajedno s njihovim količinama.
