### ISSUE TITLE
4. Nagrade

### ISSUE THREAD

**Issue by njurcic** [AIR-FOI-HR/AIR1914#14]
Prikaz mogućih nagrada za određeni broj bodova.

**Comment by jakovnakic** [comment]
Napravljen je dizajn zaslona na kojem će biti prikazane nagrade. Na vrhu je naslov, zatim prostor za recyclerview, a na dnu je kratki opis zaslona.
![image.png](https://images.zenhubusercontent.com/5de96807af4031c7dba544f4/9087ebe8-123e-40a1-8e5c-918e3ee9f78c)

**Comment by jakovnakic** [comment]
Napravljen je layout za jedan element recyclerview-a u kojem će biti prikazane sve nagrade. Jedna nagrada će sadržavati svoj naziv (koji je ujedno opis iste), te potreban broj bodova.
![image.png](https://images.zenhubusercontent.com/5de96807af4031c7dba544f4/0337a24b-cce6-402a-a1b6-a8ee9c9d2316)

**Comment by jakovnakic** [comment]
Implementirana je funkcionalnost - preko web servisa se dohvaćaju sve aktualne nagrade i prikazuju u recyclerview-u, a najveća nagrada na koju korisnik ima pravo s obzirom na svoj broj bodova je označena zelenom bojom.
![image.png](https://images.zenhubusercontent.com/5de96807af4031c7dba544f4/e4466ba4-0937-4e38-8b72-1e7c4cd920a1)
