### ISSUE TITLE
2.3.1. Detalji narudžbe

### ISSUE THREAD

**Issue by njurcic** [AIR-FOI-HR/AIR1914#15]
Odabirom na određenu narudžbu će se moći vidjeti njezini detalji (QR kod, recenzije, naručena hrana i piće, iznos).

**Comment by mjakopane** [comment]
Ako korisnik želi za određeni račun vidjeti detalje, to može učiniti na način da klikne na željeni račun. Kada korisnik odabere račun, otvori mu se novi zaslon, kao što možemo vidjeti na sljedećoj slici, i prikažu mu se detalji, tj. naziv artikla, količina, cijena i ukupna cijena. Također, u donjem lijevom kutu, odmah pokraj ukupne cijene, korisniku je prikazan gumb Ocijeni. Nakon što korisnik zaprimi svoju narudžbu, moći će ju i ocijeniti. 

Napomena: U sljedećem sprintu će na tom zaslonu biti dodani i QRkod i popust kojeg je korisnik iskoristio na tom računu. 

 ![Screenshot_20191216-235322_FOOD2GO.jpg](https://images.zenhubusercontent.com/5dc2bc6f392d6800014804f1/1b1d4485-3f12-4005-94cb-0723abffe1ae)
