### ISSUE TITLE
5.1. Unos podataka o artiklima

### ISSUE THREAD

**Issue by njurcic** [AIR-FOI-HR/AIR1914#18]
Administrator može unijeti novu kategoriju, potkategoriju (naziv, cijena, opis).

**Comment by hsostaric** [comment]
Administrator ima opciju unosa novog artikla u bazu podataka. Forma sadrži elemente za unos naziva, kolčine, cijene, opisa i vrste artikla. Slika forme vidljiva je na : http://prntscr.com/py55y0
