### ISSUE TITLE
5.2. Ažuriranje podataka o artiklima

### ISSUE THREAD

**Issue by njurcic** [AIR-FOI-HR/AIR1914#19]
Administrator može izmjenjivati sve što se tiče ili kategorije ili potkategorije (naziv hrane i pića, cijenu, opis).

**Comment by hsostaric** [comment]
Administrator pritiskom na dugme ažuriraj (Vidi sliku : http://prntscr.com/py5owh) pokreće dohvaćanje podataka za odabrani artikl tako da se GET metodom sa linka (Vidi sliku: http://prntscr.com/py5pw8) dohvaća ID artikla te se u formi (Vidi sliku: http://prntscr.com/py5qdh) prikazuju podaci o odabranom artiklu. Pritiskom na gumb "Ažururiraj" podaci za odabrani artikl se ažuriraju.
