### ISSUE TITLE
1.2. Registracija korisnika

### ISSUE THREAD

**Issue by mjakopane** [AIR-FOI-HR/AIR1914#2]
Unos općih podataka preko forme za registraciju.

**Comment by njurcic** [comment]
![Screenshot_20191205-181305_FOOD2GO.jpg](https://images.zenhubusercontent.com/5dc2bd97586229000122a2c9/1efb1074-c694-49ef-bff7-67810e03d209)

**Comment by njurcic** [comment]
Napravljen je zaslon za registraciju. Također, povezan je s glavnim zaslonom. 
Još je Web servis za registraciju u izradi.

**Comment by njurcic** [comment]
Ako korisnik unese ispravne podatke, uspješno se registrira i dobije poruku prikazanu kao na sljedećoj slici. 
![Screenshot_20191208-124824_FOOD2GO.jpg](https://images.zenhubusercontent.com/5dc2bd97586229000122a2c9/73f94716-3419-4121-b5db-aeb05147eaca)

**Comment by njurcic** [comment]
Ako korisnik upiše isti ili e-mail ili oib ili korisničko ime, on već postoji i dobije povratnu poruku da taj korisnik već postoji i da je potrebno izmijeniti parametre. 

![Screenshot_20191208-124954_FOOD2GO.jpg](https://images.zenhubusercontent.com/5dc2bd97586229000122a2c9/5344c91e-6131-49b5-a6d4-aac534cfda77)

**Comment by njurcic** [comment]
Potrebno je još implementirati provjeru za duljinu OIB-a, broj mobitela i je li e-mail pravilno napisan.

**Comment by njurcic** [comment]
Implementirana provjera duljine OIB-a, lozinke, broja mobitela i je li e-mail pravilno napisan. Osim duljine provjerava se jesu li uneseni samo brojevi kod OIB-a i broja mobitela odnosno jesu li samo slova kod imena i prezimena. Također, provjerava ima li lozinka barem jedno slovo, jedan broj, jedan znak i je li duljina lozinke barem 6 znakova. Primjer je prikazan na slici.

![NeispravanBM.jpg](https://images.zenhubusercontent.com/5dc2bd97586229000122a2c9/f260b318-8203-463e-a8e2-3656b0d1896d)
