### ISSUE TITLE
5.3. Brisanje podataka o artiklima

### ISSUE THREAD

**Issue by njurcic** [AIR-FOI-HR/AIR1914#20]
Ukoliko restoran neće više u ponudi imati određenu kategoriju ili potkategoriju, administrator će ju moći obrisati.

**Comment by hsostaric** [comment]
Funkcionalnost az brisanje odabranog artikla. Administrator pritiskom na dugme (Vidi sliku: http://prntscr.com/py5tlj) izbriše odabrani artikl iz baze podataka.
