### ISSUE TITLE
5.4. Unos podataka o nagradi

### ISSUE THREAD

**Issue by njurcic** [AIR-FOI-HR/AIR1914#21]
Same detalje o nagradi će administrator moći unositi. Ti detalji su vezani koliko je bodova potrebno da se ostvari određena nagrada ili neke druge pogodnosti.

**Comment by igradiski** [comment]
Ova funkcionalnost je pokrivena u commitu 
3356aa2 (zabunom nije oznaceno kao obavljeno)
