### ISSUE TITLE
5. Izrada Web aplikacije

### ISSUE THREAD

**Issue by njurcic** [AIR-FOI-HR/AIR1914#27]
Izrada dizajna Web aplikacije.

**Comment by igradiski** [comment]
Upload svih skripti je zavrsen, sve funkcionalnosti su odradene koje su vezane za web aplikaciju, te se ovaj  issue zatvara

**Comment by igradiski** [comment]
Dodane su nove funkcionalnosti koje su uspjesno testirane i rade kako je zamisljeno te se ovaj issue zatvara
