### ISSUE TITLE
8. Izrada wireframe-a

### ISSUE THREAD

**Issue by njurcic** [AIR-FOI-HR/AIR1914#32]
Izgled početnih zaslona kako će izgledati mobilna aplikacija.

**Comment by jakovnakic** [comment]
Početni zaslon
Prilikom pokretanja aplikacije otvara se početni zaslon. Na njemu se nalaze ime i logo aplikacije, te gumbovi za prijavu i registraciju. Prijaviti se može samo registrirani korisnik (korisnik koji već ima kreiran korisnički račun), a registrirati se može neregistrirani korisnik odnosno onaj koji još nema korisnički račun.
![1  Početni zaslon](https://user-images.githubusercontent.com/45607437/68960218-06638980-07d0-11ea-88d0-688b9e761fd0.jpg)

**Comment by jakovnakic** [comment]
Prijava
Klikom na gumb „Prijavi se“ sa početnog zaslona, otvara se novi zaslon – Prijava. Ovdje registrirani korisnik upisuje svoje korisničko ime i lozinku, a potom se prijavljuje u aplikaciju klikom na gumb „Prijavi se“. Ako je korisnik nekim slučajem zaboravio svoju lozinku, može kliknuti na „Zaboravili ste lozinku?“, čime mu se otvara zaslon za opravak lozinke.
![2  Prijava](https://user-images.githubusercontent.com/45607437/68960260-1d09e080-07d0-11ea-8ac4-1d6a8f7d8742.jpg)

**Comment by jakovnakic** [comment]
Oporavak lozinke
Klikom na „Zaboravili ste lozinku?“ sa zaslona prijave, otvara se zaslon Oporavak lozinke. Ovdje korisnik može oporaviti svoju lozinku na način da upiše svoj e-mail (onaj s kojim se registrirao) i klikne na gumb „Pošalji lozinku“. Ovim postupkom, korisnik će na e-mail primiti lozinku kojom se može prijaviti. Jednom kad se prijavi, lozinku može promijeniti u postavkama svog korisničkog računa.
![3  Oporavak lozinke](https://user-images.githubusercontent.com/45607437/68960302-3743be80-07d0-11ea-9c89-49f2216bb28a.jpg)

**Comment by jakovnakic** [comment]
Registracija
Klikom na gumb „Registriraj se“ sa početnog zaslona, otvara se zaslon Registracija. Ovo je zaslon kojim se koristi neregistrirani korisnik, a u svrhu registracije istog. Ovdje korisnik treba upisati svoje osobne podatke, te e-mail, korisničko ime, i lozinku. Kada je sve popunjeno, može se kliknuti gumb „Registriraj se“, čime se otvara zaslon za aktivaciju korisničkog računa.
![4  Registracija](https://user-images.githubusercontent.com/45607437/68960333-44f94400-07d0-11ea-9afe-acf144e13073.jpg)

**Comment by jakovnakic** [comment]
Aktivacija
Aktivacija je zaslon koji se otvara kada se neregistrirani korisnik registrira odnosno kada isti klikne na „Registriraj se“ sa zaslona registracije. Klikom na spomenuti gumb se otvara ovaj zaslon, te se na e-mail korisnika šalje aktivacijski kod koji korisnik na ovom zaslonu treba upisati kako bi aktivirao svoj korisnički račun.
![5  Aktivacija](https://user-images.githubusercontent.com/45607437/68960380-59d5d780-07d0-11ea-9338-95f22fa949a4.jpg)

**Comment by jakovnakic** [comment]
Glavni zaslon
Ovo je glavni zaslon koji se otvara kada se registrirani korisnik prijavi. Na vrhu, ikona sa tri vodoravne crte služi za prikazivanje i sakrivanje izbornika. Ispod aplikacijske trake prikazana je lista različitih kategorija. Klikom na jednu od kategorija, otvara se zaslon koji prikazuje sve artikle iz te kategorije.
![6  Glavni zaslon](https://user-images.githubusercontent.com/45607437/68960408-665a3000-07d0-11ea-9ae5-673b827f1df8.jpg)

**Comment by jakovnakic** [comment]
Izbornik
Klikom na ikonu sa tri vodoravne crtice, prikazuje se izbornik. Na vrhu se nalazi slika, ime i prezime korisnika. Ispod se nalaze gumbovi koji otvaraju istoimene zaslone. Zadnji gumb, „Odjava“, odjavljuje korisnika te ga vraća na početni zaslon. 
![7  Izbornik](https://user-images.githubusercontent.com/45607437/68960461-825dd180-07d0-11ea-825a-a52d7224344c.jpg)

**Comment by jakovnakic** [comment]
Kategorija
Klikom na jednu od kategorija sa glavnog zaslona, otvara se zaslon sa detaljima te kategorije, odnosno prikazuju se svi artikli iz te kategorije. Uz svaki artikl, prikazana je i njegova jedinična cijena, te ikona sa lijeve strane.
![8  Kategorija](https://user-images.githubusercontent.com/45607437/68960503-8f7ac080-07d0-11ea-962c-854cb8342f78.jpg)

**Comment by jakovnakic** [comment]
Artikl
Klikom na jedan od artikala sa zaslona kategorije, otvara se zaslon na kojem su prikazani detalji odabranog artikla. Prikazani su ime, slika, opis, te cijena artikla. Klikom na „Dodaj u košaricu“, artikl se dodaje u košaricu odnosno kreira se nova narudžba (ako već ne postoji) i u nju se dodaje odabrani artikl, ili se dodaje odabrani artikl na već postojeću narudžbu (ako ona već postoji).
![9  Artikl](https://user-images.githubusercontent.com/45607437/68960560-b0dbac80-07d0-11ea-8540-216787a45d9f.jpg)

**Comment by jakovnakic** [comment]
Postavke
Klikom na gumb „Postavke“ sa izbornika, otvara se istoimeni zaslon. Ovdje korisnik može promijeniti svoje osobne podatke te jezik aplikacije. Nakon bilokakvih promjena, treba kliknuti na gumb „Spremi“ kako bi se promjene pohranile.
![10  Postavke](https://user-images.githubusercontent.com/45607437/68960586-be913200-07d0-11ea-92a7-e3b990445612.jpg)

**Comment by jakovnakic** [comment]
Stanje bodova
Klikom na gumb „Stanje bodova“ sa izbornika, otvara se istoimeni zaslon. Ovdje korisnik može vidjeti trenutan broj bodova. Bodovi se skupljaju svaki put kad korisnik izvrši narudžbu, a broj bodova koji se dobiva ovisi o veličini iste. Bodovi se mogu iskoristiti kod naručivanja za ostvarivanje popusta.
![11  Stanje bodova](https://user-images.githubusercontent.com/45607437/68960619-cfda3e80-07d0-11ea-99f0-2b55d1572951.jpg)

**Comment by jakovnakic** [comment]
Nagrade
Klikom na gumb „Nagrade“ sa izbornika, otvara se istoimeni zaslon. Ovdje korisnik može vidjeti trenutno aktualne nagrade. Zeleno označena nagrada je ona na koju korisnik ima pravo s obzirom na svoj trenutni broj bodova. Ako nijedna nagrada nije označena zeleno bojom, to znači da korisnik nema dovoljno skupljenih bodova ni za najmanju nagradu.
![12  Nagrade](https://user-images.githubusercontent.com/45607437/68960654-dec0f100-07d0-11ea-8308-28bca8615a4b.jpg)

**Comment by jakovnakic** [comment]
Trenutna narudžba
Klikom na gumb „Trenutna narudžba“ sa izbornika, otvara se istoimeni zaslon. Ovdje korisnik može vidjeti sve artikle koje namjerava naručiti. Uz artikl, prikazana je i njegova ikona, jedinična cijena, te količina u kojoj korisnik želi naručiti istog. Na dnu, u lijevom kutu, prikazana je ukupna cijena narudžbe, a u desnom kutu dva gumba. Gumb „Iskoristi bodove“ služi za iskorištavanje popusta (ukoliko korisnik ima pravo na njega), a gumbom „Naruči“ se narudžba izvršava.
![13  Trenutna narudžba](https://user-images.githubusercontent.com/45607437/68960668-ea141c80-07d0-11ea-9048-2296be19f934.jpg)

**Comment by jakovnakic** [comment]
Iskoristi bodove
Klikom na gumb „Iskoristi bodove“ sa zaslona trenutne narudžbe, otvara se prozorčić u kojem se pita korisnika želi li uistinu iskoristiti popust na trenutnu narudžbu. Korisnik ima pravo samo na najbolju nagradu s obzirom na svoje trenutne bodove. Naravno, korisnik koji nema dovoljno bodova za bilokakvu nagradu niti ne može kliknuti na gumb „Iskoristi bodove“ odnosno za njega je gumb onemogućen. 
![14  Iskoristi bodove](https://user-images.githubusercontent.com/45607437/68960697-fbf5bf80-07d0-11ea-8939-13144d7c0cda.jpg)

**Comment by jakovnakic** [comment]
Naruči
Klikom na gumb „Naruči“ sa zaslona trenutne narudžbe, otvara se prozorčić u kojem se potvrđuje korisniku da je narudžba zaprimljena te da će korisnik dobiti račun na svoj e-mail.
![15  Naruči](https://user-images.githubusercontent.com/45607437/68960725-0a43db80-07d1-11ea-88ef-0f2b90140b4d.jpg)

**Comment by jakovnakic** [comment]
Moje narudžbe
Klikom na gumb „Moje narudžbe“ sa izbornika, otvara se istoimeni zaslon. Ovdje korisnik može vidjeti sve svoje prethodne narudžbe (ako ih ima). Uz svaku narudžbu prikazano je nekoliko artikala iste, datum izvršavanja narudžbe, te ukupna cijena.
![16  Moje narudžbe](https://user-images.githubusercontent.com/45607437/68960734-14fe7080-07d1-11ea-81bb-c6a104720a42.jpg)

**Comment by jakovnakic** [comment]
Detalji narudžbe
Klikom na jednu od narudžbi, otvara se prozorčić sa detaljima iste. Ovdje se mogu vidjeti svi artikli odabrane narudžbe, zajedno sa njihovom jediničnom cijenom i količinom u kojoj su bili naručeni. Na dnu je prikazana ukupna cijena narudžbe.
![17  Detalji narudžbe](https://user-images.githubusercontent.com/45607437/68960753-1fb90580-07d1-11ea-9c1f-ca9c1dc538ea.jpg)

**Comment by jakovnakic** [comment]
Ispravak zaslona Izbornik
Dodan je gumb "Nagrade" koji otvara istoimeni zaslon.
![7  Izbornik](https://user-images.githubusercontent.com/45607437/70355743-2d632780-1873-11ea-98fe-c2b46559e0f1.jpg)

**Comment by jakovnakic** [comment]
Ispravak zaslona Oporavak lozinke
Dodan je textbox za unos korisničkog imena.
![3  Oporavak lozinke](https://user-images.githubusercontent.com/45607437/70355867-6e5b3c00-1873-11ea-9f62-0daa7bcac717.jpg)

**Comment by jakovnakic** [comment]
Ispravak Glavnog zaslona
Postoje dvije kategorije artikala - hrana, i piće.
![6  Glavni zaslon](https://user-images.githubusercontent.com/45607437/70355958-9c408080-1873-11ea-9263-03a158eea46c.jpg)

**Comment by jakovnakic** [comment]
Dodan je novi zaslon - Plaćanje
Klikom na gumb „Naruči“ sa zaslona trenutne narudžbe, otvara se prozorčić u kojem se trebaju upisati podaci o kreditnoj kartici kojom korisnik namjerava platiti narudžbu. Nakon popunjavanja podataka, klikom na gumb „Plati“ izvršava se transakcija.
![15  Plaćanje](https://user-images.githubusercontent.com/45607437/70356005-b5493180-1873-11ea-8430-55d419deffbe.jpg)

**Comment by jakovnakic** [comment]
Popravljen je zaslon za prikaz artikla
- dodani su gumbovi "+" i "-" za povećanje i smanjenje količine artikla koja se stavlja u košaricu
![9  Artikl](https://user-images.githubusercontent.com/45607437/70798199-992f1e00-1da6-11ea-9c36-bd33909c72ab.jpg)

**Comment by jakovnakic** [comment]
Popravljen je zaslon za prikaz trenutne narudžbe
- dodani su gumbovi "+" i "-" za povećanje i smanjenje količine artikla u košarici
![13  Trenutna narudžba](https://user-images.githubusercontent.com/45607437/70798332-edd29900-1da6-11ea-8d23-4fdf0b8def9e.jpg)

**Comment by jakovnakic** [comment]
Popravljen je dijaloški okvir u kojem se prikazuju detalji odabrane prethodne narudžbe
- dodan je gumb za ocjenjivanje (davanje povratne informacije)
![18  Detalji narudžbe](https://user-images.githubusercontent.com/45607437/70798402-296d6300-1da7-11ea-9b9b-009da936379d.jpg)

**Comment by jakovnakic** [comment]
Kreiran je novi dijaloški okvir - Povratna informacija
- dijaloški okvir se otvara klikom na gumb "Ocijeni" iz dijaloškog okvira za prikaz detalja narudžbe
- moguće je dati ocjenu (1-5) i komentar
![19  Povratna informacija](https://user-images.githubusercontent.com/45607437/70798511-69cce100-1da7-11ea-8cc3-f5bf492478fa.jpg)

**Comment by jakovnakic** [comment]
Popravljen je zaslon Moje narudžbe
- za svaku narudžbu je prikazan broj narudžbe, datum, i iznos
![image](https://user-images.githubusercontent.com/45607437/71179411-68505c80-2270-11ea-9ce5-d62bc113c093.png)

**Comment by jakovnakic** [comment]
Popravljen je prikaz Računa odnosno detalja narudžbe
- prikazuje se na novom zaslonu, a ne u dijaloškom okviru
- tablično je strukturiran
- za svaki artikl se prikazuje ikona
![image](https://user-images.githubusercontent.com/45607437/71179555-b5ccc980-2270-11ea-8084-106bc9c97bef.png)

**Comment by jakovnakic** [comment]
Popravljen je zaslon za Povratnu informaciju
- dijaloški okvir se otvara klikom na gum "Ocijeni" sa zaslona Račun
![image](https://user-images.githubusercontent.com/45607437/71179620-d85ee280-2270-11ea-89cd-1acfdc5ba13d.png)

**Comment by jakovnakic** [comment]
Popravljen je zaslon Stanje bodova
Klikom na gumb „Stanje bodova“ sa izbornika, otvara se istoimeni zaslon. Ovdje korisnik može vidjeti trenutan broj bodova. Bodovi se skupljaju svaki put kad korisnik unese PIN ili skenira QR kod. QR kod ili PIN se dobiva s računom svaki put kada korisnik izvrši narudžbu, a broj bodova koji se može ostvariti ovisi o veličini narudžbe. Na zaslonu postoji gumb „Ažuriraj bodove“, klikom na njega se otvara prozor u kojem je moguće unijeti PIN ili skenirati QR kod, ovisno o tome je li „prekidač“ sa zaslona Stanje bodova uključen ili isključen. Bodovi se mogu iskoristiti kod naručivanja za ostvarivanje popusta.
![Stanje bodova](https://user-images.githubusercontent.com/45607437/73485529-88ad2400-43a3-11ea-8bff-1d645fac9553.png)

**Comment by jakovnakic** [comment]
Kreiran je zaslon za skeniranje QR koda
Klikom na gumb „Ažuriraj bodove“ sa zaslona Stanje bodova dok je prekidač uključen, otvara se prozor za skeniranje QR koda. Kada korisnik ispravno pozicionira kameru i stavi u fokus ispravni QR kod, klikom na gumb „Ažuriraj bodove“ QR kod se skenira i ažuriraju se bodovi korisnika. Broj bodova koji nosi QR kod u proporcionalnom je odnosu sa veličinom narudžbe kojom je QR kod dobiven.
![qr_kod](https://user-images.githubusercontent.com/45607437/73485615-b5613b80-43a3-11ea-8c35-8d4ed976a142.png)

**Comment by jakovnakic** [comment]
Kreiran je zaslon za unos PIN-a
Klikom na gumb „Ažuriraj bodove“ sa zaslona Stanje bodova dok je prekidač isključen, otvara se prozor za unos PIN-a. Kada korisnik unese ispravan PIN, klikom na gumb „Ažuriraj bodove“ ažuriraju se bodovi korisnika. Broj bodova koji nosi PIN u proporcionalnom je odnosu sa veličinom narudžbe kojom je PIN dobiven.
![pin](https://user-images.githubusercontent.com/45607437/73485667-d2960a00-43a3-11ea-854c-6a135e92439c.png)
