### ISSUE TITLE
2. Izbornik

### ISSUE THREAD

**Issue by mjakopane** [AIR-FOI-HR/AIR1914#5]
Pomoću izbornika korisnik će moći pristupiti slijedećim funkcionalnostima: Moje narudžbe, Stanje bodova, Trenutna narudžba, Postavke i Odjava. Također, na izborniku će biti prikazana slika korisnika i njegovo ime i prezime.

**Comment by hsostaric** [comment]
![izbornik](https://user-images.githubusercontent.com/37140133/70537232-672c7a80-1b60-11ea-9ba0-3bf487602235.jpg)

Navigacijski izbornik sa opcijama koje vode na fragmente s funkcionalnostima naše aplikacije.


![glavni_ekran](https://user-images.githubusercontent.com/37140133/70537600-00f42780-1b61-11ea-980b-b8012e8c3216.jpg)
Prikaz početnog zaslona sa ikonicom "hamburgerom", na čiji klik se otvara bočni izbornik
