### ISSUE TITLE
10. Provjera internet konekcije

### ISSUE THREAD

**Issue by mjakopane** [AIR-FOI-HR/AIR1914#51]
Prije bilo kakve aktivnosti u aplikaciji potrebno je napraviti provjeru je li korisnik spojen na Internet.

**Comment by mjakopane** [comment]
Napravljena klasa Internet koja u sebi sadrži metodu za provjeru Internet konekcije, tj. je li korisnik povezan sa Internetom. Ako nije, tada korisnik dobije upozorenje da se mora prijaviti na Internet.

**Comment by njurcic** [comment]
Prethodni komentar prikazan na slici. 

![Screenshot_20191206-193842_FOOD2GO.jpg](https://images.zenhubusercontent.com/5dc2bd97586229000122a2c9/110cf9d0-ba27-42ab-b564-c57fd03a496d)

**Comment by njurcic** [comment]
Napomena: Dodana je provjera samo na zaslon prijave. Ostale će se dodavati kako se budu implementirali ostali zasloni.
