### ISSUE TITLE
2.1. Trenutna narudžba

### ISSUE THREAD

**Issue by mjakopane** [AIR-FOI-HR/AIR1914#6]
Korisnik ima mogućnost vidjeti svoju trenutnu narudžbu. Omogućava prikaz svih jela i pića koja je naručio sve do trenutka dostave.

**Comment by njurcic** [comment]
Prije nego se potvrdi narudžba korisnik može iskoristiti nagradu i na taj način se može ostvariti popust. To se jedino može iskoristiti ako korisnik ima osvojenih nagrada na temelju sakupljenih bodova.

**Comment by njurcic** [comment]
Također, na tom zaslonu će se omogućiti unos recenzije, tj. komentiranje narudžbe i ocjena.

**Comment by hsostaric** [comment]
![image.png](https://images.zenhubusercontent.com/5dc312a3ce55cf0001c090d0/0e9235ed-6c26-4996-bd7f-e54d60269469)
Prikaz ekrana koji prikazuje našu trenutnu košaricu artikala za naručivanje. Povećavanjem i smanjenjem količine smanjuje se ukupna cijena za plaćanje.

**Comment by hsostaric** [comment]
![image.png](https://images.zenhubusercontent.com/5dc312a3ce55cf0001c090d0/6edc85c7-b385-4e3b-b0ec-394db8a80a2e)

U slučaju da korisnik želi iskoristiti bodove vjernosti popust mu se uračuna u ukupnu cijenu.
![image.png](https://images.zenhubusercontent.com/5dc312a3ce55cf0001c090d0/acb8a0af-44bf-4201-8696-d05195003ca8)
Nakon pritiska na dugme "Naruci" javlja mu se poruka o uspjehu kupovine.
![image.png](https://images.zenhubusercontent.com/5dc312a3ce55cf0001c090d0/10ea8a34-3118-4920-b199-f6d70f85fb80)

Ova funkcionalnost će u sljedećem sprintu biti nadograđena s mogućnosti plaćanja kako bi tražena narudžba izvršila.
