### ISSUE TITLE
2.3.2. Povratna informacija

### ISSUE THREAD

**Issue by njurcic** [AIR-FOI-HR/AIR1914#68]
Korisnik će imati mogućnost ocijeniti račun.

**Comment by mjakopane** [comment]
Kada korisnik odabere opciju Ocijeni, na zaslonu Detalji narudžbe, prikaže mu se sljedeći zaslon, koji je prikazan na sljedećoj slici. Korisnik će ocijeniti restoran, hranu, dostavu kroz komentar i bodove. Komentare će ostavljati u tekstualnom obliku, a bodove kroz zvjezdice, tj. rating bar. Kako bi ocjenjivanje bilo uspješno, korisnik treba oboje ispuniti, komentar i zvjezdice, i dobit će poruku da je ocjenjivanje prošlo uspješno i ti podaci će se spremiti u bazu podataka. Ukoliko ocjenjivanje ne prođe uspješno, korisnik je nešto zaboravio ispuniti, obavijestit će ga aplikacija kroz poruku. 

![Screenshot_20191216-235411_FOOD2GO.jpg](https://images.zenhubusercontent.com/5dc2bc6f392d6800014804f1/b564a5ac-c360-469a-8b7f-e2150e2c1c68)
