### ISSUE TITLE
2.2. Stanje bodova

### ISSUE THREAD

**Issue by mjakopane** [AIR-FOI-HR/AIR1914#7]
Prikazuje sve bodove koje je korisnik sakupio dosadašnjim narudžbama.

**Comment by jakovnakic** [comment]
Napravljen je dizajn za zaslon stanje bodova i implementirana je funkcionalnost dohvaćanja korisnikovih trenutnih bodova te prikaz istih na zaslonu.
![image.png](https://images.zenhubusercontent.com/5de96807af4031c7dba544f4/8e243e78-5300-4004-8057-96d109169dcb)
