### ISSUE TITLE
2.4. Postavke

### ISSUE THREAD

**Issue by mjakopane** [AIR-FOI-HR/AIR1914#9]
Ukoliko korisnik želi izmijeniti osobne podatke (adresa, mobitel, lozinka...), to može učiniti u postavkama.

**Comment by hsostaric** [comment]
![settings.jpg](https://images.zenhubusercontent.com/5dc312a3ce55cf0001c090d0/5459568c-201a-4154-8f34-8b0ba4bfec02)
Na ovome ekranu  prijavljeni korisnik ima mogućnost uređivat svoje osobne podatke kao što su korisničko ime, ime, prezime, adresa i sl. u slučaju da se odaberu korisničko ime ili email adresa koji su zauzeti ispisuje se   poruka o neuspjehu.
![settings2.jpg](https://images.zenhubusercontent.com/5dc312a3ce55cf0001c090d0/693c72c7-711e-472c-91d5-3a48ae55b0d2)
